In [36]:
import numpy as np

In [37]:
"""
Here I create a unitary gate which is able to re-create any unitary quantum gate, in this case the parameters are chosen so that we can
have the X-gate
"""

def unitary(theta,phi,lmbda):
    a = np.cos(theta/2)
    b = -(np.exp(1j*lmbda)*np.sin(theta/2))
    c = np.exp(1j*phi)*np.sin(theta/2)
    d = np.exp((1j*(phi+lmbda)))*np.cos(theta/2)
    Matrix = np.matrix([[a,b],[c,d]])
    return np.abs(np.round(Matrix.real)) #rounding and absolute value are taken care of for a simple 0,1 matrix. 

In [38]:
def bloc_function(n): # n number is qubits involved (i.e. cx=2, ccx=3, cccx=4)
    X_gate = unitary(np.pi,0,np.pi)
    if n<2: # if n <2 then its impossible to build a control gate (self explanatory)
        return("Please input a number equal to or greater than 2")
    n = n-2 # number of qubits after 2, number stays fixed... it will used for iteration limit
    counts =0 # number that will be used as a counter for qubit iteration assuming an initial 2 qubits (i.e. 2 qb -> counts=0, 3 qb -> counts=1 and so forth)
    while counts<=n:   # start with number of counts as 0, and increase by one everytime you increase a qubit (build from the ground up)
        N = 2**(counts+2) #dimensions of the matrix given the number of counts iteration
        Id = np.identity(int(N/2))  #identity matrix occupying half of the dimensions
        zero = np.zeros((int(N/2),int(N/2))) # zero matrix occupying half of the dimensions
        P1 = np.concatenate((Id,zero),axis=1)  #concatenate the former matrix horizontally resulting in the upper half of the matrix filled. 
        if N==4:
            P2 = np.concatenate((zero,X_gate),axis=1) # IF N=4 then we just need to concatenate the lower half of the matrix together (zeros with X_gate)
        else:
            P2 = np.concatenate((zero,P3),axis=1) #ELSE use P3 which in this case should be a variable from the previous iteration to concatenate zeros with itself.
        
        P3 = np.concatenate((P1,P2),axis=0) # concatenate P1 and P2 together (upper half and lower half of the square matrix respectively)
        counts = counts+1 # increase number of counts by 1
        
    return P3


In [39]:
bloc_function(2)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]])

In [33]:
bloc_function(3)

matrix([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1., 0.]])

In [34]:
bloc_function(4)

matrix([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

In [35]:
n = input("Please input the number of qubits involved (minimum 2): " )
bloc_function(int(n))

Please input the number of qubits involved (minimum 2):  6


matrix([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 1., 0.]])